config/routes.rb
Books::Application.routes.draw do

  devise_for :users

  get "home/index"

  resources :statuses

  resources :books

  resources :categories

  root :to => 'home#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :author, :category_id, :description, :name, :status_id, :user_id

  validates_presence_of :name, :author
  validates_associated :category
  validates_associated :user

  belongs_to :category
  belongs_to :status
  belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :books

  def destroy
    super if books.count == 0
  end
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :name

  has_one :book

  def destroy
    super if book.nil?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :authenticate_user!

  # GET /books
  # GET /books.json
  def index
    @books = Book.where(user_id: current_user)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])
    @book.user = current_user

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    
    respond_to do |format|
      if @category.destroy
        format.html { redirect_to categories_url }
        format.json { head :no_content }
      else
        format.html { redirect_to categories_url, error: 'Category was not destroyed'  }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/books/_form.html.erb
<%= form_for @book, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> /Book</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :author, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :author, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :category_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.collection_select(:category_id, Category.all, :id, :name) %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :description, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :status_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.collection_select(:status_id, Status.all, :id, :name) %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', books_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/books/edit.html.erb
<%= render :partial => 'form' %>

app/views/books/index.html.erb
<h1>Books</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.id %></td>
        <td><%= link_to book.name, book_path(book) %></td>
        <td><%= book.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_book_path(book), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', book_path(book), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_book_path, :class => 'btn btn-primary' %>

app/views/books/new.html.erb
<%= render :partial => 'form' %>

app/views/books/show.html.erb
<h1>/Book</h1>

<p>
  <b>Name</b><br>
  <%= @book.name %>
</p>

<p>
  <b>Author</b><br>
  <%= @book.author %>
</p>

<p>
  <b>Category</b><br>
  <%= @book.category.name %>
</p>

<p>
  <b>Description</b><br>
  <%= @book.description %>
</p>

<p>
  <b>Status</b><br>
  <%= @book.status.name %>
</p>

<div class="form-actions">
  <%= link_to 'Back', books_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_book_path(@book), :class => 'btn' %>
  <%= link_to 'Delete', book_path(@book), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>

app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> /Category</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', categories_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/categories/edit.html.erb
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<h1>Categorys</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= link_to category.name, category_path(category) %></td>
        <td><%= category.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_category_path(category), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', category_path(category), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_category_path, :class => 'btn btn-primary' %>

app/views/categories/new.html.erb
<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<h1>/Category</h1>

<p>
  <b>Name</b><br>
  <%= @category.name %>
</p>

<div class="form-actions">
  <%= link_to 'Back', categories_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_category_path(@category), :class => 'btn' %>
  <%= link_to 'Delete', category_path(@category), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<p><%= current_user.inspect %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Books</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Books</a>
          <div class="container nav-collapse">
            <ul class="nav">
                <% if user_signed_in? %>
                  <li><%= link_to('Books managment', books_path) %></li>
                  <li><%= link_to('Categories managment', categories_path) %></li>
                  <li><%= link_to('Statuses managment', statuses_path) %></li>
                  <li>&nbsp;</li>
                  <li><%= link_to('Edit registration', edit_user_registration_path) %></li>
                  <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
                <% else %>
                  <li><%= link_to('Register', new_user_registration_path)  %></li>
                  <li><%= link_to('Login', new_user_session_path)  %></li>
                <% end %>

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div id="flashes" style="display:none">
          <% if flash[:alert] %><span class="alert"><%= flash[:alert] %></span><% end %>
          <% if flash[:notice] %><span class="notice"><%= flash[:notice] %></span><% end %>
          <% if flash[:error] %><span class="error"><%= flash[:error] %></span><% end %>
        </div>
        
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                    <li><%= link_to "Link1", "/path1"  %></li>
                    <li><%= link_to "Link2", "/path2"  %></li>
                    <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/statuses/_form.html.erb
<%= form_for @status, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> /Status</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', statuses_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/statuses/edit.html.erb
<%= render :partial => 'form' %>

app/views/statuses/index.html.erb
<h1>Statuss</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.id %></td>
        <td><%= link_to status.name, status_path(status) %></td>
        <td><%= status.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_status_path(status), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', status_path(status), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_status_path, :class => 'btn btn-primary' %>

app/views/statuses/new.html.erb
<%= render :partial => 'form' %>

app/views/statuses/show.html.erb
<h1>/Status</h1>

<p>
  <b>Name</b><br>
  <%= @status.name %>
</p>

<div class="form-actions">
  <%= link_to 'Back', statuses_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_status_path(@status), :class => 'btn' %>
  <%= link_to 'Delete', status_path(@status), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>